---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Get index.html
    uri:
      url: http://localhost:5061
      return_content: yes
    register: this

  - name: Ensure content type is text/html
    assert:
      that:
      - "'text/html' in this.content_type"
